### ISSUE TITLE
docs: contribution guide updates

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/cookiecutter-invenio-module#26]
- [ ] Get Started mentions ``invenio`` explicit instead of ``{{ cookiecutter.project_shortname }}``
- [ ] Example in (6) of commit message should update.
- [ ] Bullet (5) should mention which tests are being run.

**Comment by nharraud** [comment]
the link to travis is not the correct one. It should be `https://travis-ci.org/...` instead of `https://travis-ci.com/...`. I just tried clicking on the one generated and it sends to travis pro, which says that the project does not exist. It seems that travis-pro is completely separated from the travis-ci we use.
